CREATE TABLE notification_tasks
(
    id                      BIGINT generated by default as identity primary key,
    message                 TEXT NOT NULL ,
    chat_id                 BIGINT NOT NULL,
    notification_data_time TIMESTAMP NOT NULL
);